version: 0.2

phases:
  pre_build:
    commands:
    - echo "Logging in to DockerHub..."
    - echo "123456789" | docker login -u "quangtung" --password-stdin
    - npm install
    - npm run test

  build:
    commands:
    - echo "Building your application..."
    - docker build -t due .
    - docker tag due quangtung20/due:latest

  post_build:
    commands:
    - echo "Pushing the Docker image to DockerHub..."
    - docker push quangtung20/due:latest
    - printf '[{"name":"fgms-due","imageUri":"%s"}]' quangtung20/due:latest > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
