version: 0.2

phases:
  pre_build:
    commands:
    - echo "Logging in to DockerHub..."
    - echo "123456789" | docker login -u "quangtung" --password-stdin

  build:
    commands:
    - echo "Building your application..."
    - docker build -t uno .
    - docker tag uno quangtung20/uno:latest

  post_build:
    commands:
    - echo "Pushing the Docker image to DockerHub..."
    - docker push quangtung20/uno:latest
    - printf '[{"name":"fgms-uno","imageUri":"%s"}]' quangtung20/uno:latest > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
